# coding: utf-8

"""
    Wealthport API

    Wealthport provides a simple, lightweight and open Web API based on the Open API 2.0 standard (<a href=\"https://www.openapis.org\" target=\"_blank\">https://www.openapis.org</a>). Our APIs offer a variety of operations related to managing Sources, Folders, Orders and Recipes. There are operations to submit and track Jobs, upload and download data files and many more.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """ OrdersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.orders_api.OrdersApi()

    def tearDown(self):
        pass

    def test_create_order(self):
        """
        Test case for create_order

        Create Order
        """
        pass

    def test_delete_order(self):
        """
        Test case for delete_order

        Delete Order
        """
        pass

    def test_get_result(self):
        """
        Test case for get_result

        Get Result
        """
        pass

    def test_get_status(self):
        """
        Test case for get_status

        Get Status
        """
        pass

    def test_retrieve_order(self):
        """
        Test case for retrieve_order

        Retrieve Order
        """
        pass

    def test_retrieve_orders(self):
        """
        Test case for retrieve_orders

        Retrieve Orders
        """
        pass

    def test_submit_order(self):
        """
        Test case for submit_order

        Submit Order
        """
        pass

    def test_update_order(self):
        """
        Test case for update_order

        Update Order
        """
        pass


if __name__ == '__main__':
    unittest.main()
