# coding: utf-8

"""
    Wealthport API

    Wealthport provides a simple, lightweight and open Web API based on the Open API 2.0 standard (<a href=\"https://www.openapis.org\" target=\"_blank\">https://www.openapis.org</a>). Our APIs offer a variety of operations related to managing Sources, Folders, Orders and Recipes. There are operations to submit and track Jobs, upload and download data files and many more.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.sources_api import SourcesApi


class TestSourcesApi(unittest.TestCase):
    """ SourcesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.sources_api.SourcesApi()

    def tearDown(self):
        pass

    def test_create_source(self):
        """
        Test case for create_source

        Create Source
        """
        pass

    def test_delete_source(self):
        """
        Test case for delete_source

        Delete Source
        """
        pass

    def test_get_download_url(self):
        """
        Test case for get_download_url

        Download File
        """
        pass

    def test_get_upload_url(self):
        """
        Test case for get_upload_url

        Upload File
        """
        pass

    def test_retrieve_source(self):
        """
        Test case for retrieve_source

        Retrieve Source
        """
        pass

    def test_retrieve_sources(self):
        """
        Test case for retrieve_sources

        Retrieve Sources
        """
        pass

    def test_update_source(self):
        """
        Test case for update_source

        Update Source
        """
        pass


if __name__ == '__main__':
    unittest.main()
