# coding: utf-8

"""
    Wealthport API

    Wealthport provides a simple, lightweight and open Web API based on the Open API 2.0 standard (<a href=\"https://www.openapis.org\" target=\"_blank\">https://www.openapis.org</a>). Our APIs offer a variety of operations related to managing Sources, Folders, Orders and Recipes. There are operations to submit and track Jobs, upload and download data files and many more.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.archivable_object import ArchivableObject
from .models.existing_folder import ExistingFolder
from .models.existing_order import ExistingOrder
from .models.existing_recipe import ExistingRecipe
from .models.existing_source import ExistingSource
from .models.folder_request import FolderRequest
from .models.order_request import OrderRequest
from .models.source_request import SourceRequest

# import apis into sdk package
from .apis.folders_api import FoldersApi
from .apis.orders_api import OrdersApi
from .apis.recipes_api import RecipesApi
from .apis.sources_api import SourcesApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
