# coding: utf-8

"""
    Wealthport API

    Wealthport provides a simple, lightweight and open Web API based on the Open API 2.0 standard (<a href=\"https://www.openapis.org\" target=\"_blank\">https://www.openapis.org</a>). Our APIs offer a variety of operations related to managing Sources, Folders, Orders and Recipes. There are operations to submit and track Jobs, upload and download data files and many more.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ExistingSource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, created=None, creator=None, mime=None, encoding=None, folder=None, bytes=None, folder_name=None):
        """
        ExistingSource - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'name': 'str',
            'created': 'datetime',
            'creator': 'str',
            'mime': 'str',
            'encoding': 'str',
            'folder': 'str',
            'bytes': 'int',
            'folder_name': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'created': 'created',
            'creator': 'creator',
            'mime': 'mime',
            'encoding': 'encoding',
            'folder': 'folder',
            'bytes': 'bytes',
            'folder_name': 'folderName'
        }

        self._id = id
        self._name = name
        self._created = created
        self._creator = creator
        self._mime = mime
        self._encoding = encoding
        self._folder = folder
        self._bytes = bytes
        self._folder_name = folder_name

    @property
    def id(self):
        """
        Gets the id of this ExistingSource.
        Unique ID of the source

        :return: The id of this ExistingSource.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ExistingSource.
        Unique ID of the source

        :param id: The id of this ExistingSource.
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")
        if id is not None and len(id) > 36:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `36`")
        if id is not None and len(id) < 36:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `36`")

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this ExistingSource.
        Name of the source

        :return: The name of this ExistingSource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ExistingSource.
        Name of the source

        :param name: The name of this ExistingSource.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name

    @property
    def created(self):
        """
        Gets the created of this ExistingSource.
        ISO 8601 Date when the source has been created

        :return: The created of this ExistingSource.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this ExistingSource.
        ISO 8601 Date when the source has been created

        :param created: The created of this ExistingSource.
        :type: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")

        self._created = created

    @property
    def creator(self):
        """
        Gets the creator of this ExistingSource.
        User ID of the user that created the source

        :return: The creator of this ExistingSource.
        :rtype: str
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """
        Sets the creator of this ExistingSource.
        User ID of the user that created the source

        :param creator: The creator of this ExistingSource.
        :type: str
        """
        if creator is None:
            raise ValueError("Invalid value for `creator`, must not be `None`")
        if creator is not None and len(creator) > 36:
            raise ValueError("Invalid value for `creator`, length must be less than or equal to `36`")
        if creator is not None and len(creator) < 36:
            raise ValueError("Invalid value for `creator`, length must be greater than or equal to `36`")

        self._creator = creator

    @property
    def mime(self):
        """
        Gets the mime of this ExistingSource.
        MIME type of the source

        :return: The mime of this ExistingSource.
        :rtype: str
        """
        return self._mime

    @mime.setter
    def mime(self, mime):
        """
        Sets the mime of this ExistingSource.
        MIME type of the source

        :param mime: The mime of this ExistingSource.
        :type: str
        """
        allowed_values = ["text/csv", "text/tab-separated-values", "text/x-bar-separated-values", "text/x-semicolon-separated-values", "application/x-ldjson", "application/xml", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
        if mime not in allowed_values:
            raise ValueError(
                "Invalid value for `mime` ({0}), must be one of {1}"
                .format(mime, allowed_values)
            )

        self._mime = mime

    @property
    def encoding(self):
        """
        Gets the encoding of this ExistingSource.
        Encoding of the source

        :return: The encoding of this ExistingSource.
        :rtype: str
        """
        return self._encoding

    @encoding.setter
    def encoding(self, encoding):
        """
        Sets the encoding of this ExistingSource.
        Encoding of the source

        :param encoding: The encoding of this ExistingSource.
        :type: str
        """
        if encoding is not None and len(encoding) > 2147483647:
            raise ValueError("Invalid value for `encoding`, length must be less than or equal to `2147483647`")
        if encoding is not None and len(encoding) < 1:
            raise ValueError("Invalid value for `encoding`, length must be greater than or equal to `1`")

        self._encoding = encoding

    @property
    def folder(self):
        """
        Gets the folder of this ExistingSource.
        Optional folder ID of the folder containing the source

        :return: The folder of this ExistingSource.
        :rtype: str
        """
        return self._folder

    @folder.setter
    def folder(self, folder):
        """
        Sets the folder of this ExistingSource.
        Optional folder ID of the folder containing the source

        :param folder: The folder of this ExistingSource.
        :type: str
        """
        if folder is not None and len(folder) > 36:
            raise ValueError("Invalid value for `folder`, length must be less than or equal to `36`")
        if folder is not None and len(folder) < 36:
            raise ValueError("Invalid value for `folder`, length must be greater than or equal to `36`")

        self._folder = folder

    @property
    def bytes(self):
        """
        Gets the bytes of this ExistingSource.
        Size of the source (in bytes)

        :return: The bytes of this ExistingSource.
        :rtype: int
        """
        return self._bytes

    @bytes.setter
    def bytes(self, bytes):
        """
        Sets the bytes of this ExistingSource.
        Size of the source (in bytes)

        :param bytes: The bytes of this ExistingSource.
        :type: int
        """
        if bytes is None:
            raise ValueError("Invalid value for `bytes`, must not be `None`")
        if bytes is not None and bytes < -1:
            raise ValueError("Invalid value for `bytes`, must be a value greater than or equal to `-1`")

        self._bytes = bytes

    @property
    def folder_name(self):
        """
        Gets the folder_name of this ExistingSource.

        :return: The folder_name of this ExistingSource.
        :rtype: str
        """
        return self._folder_name

    @folder_name.setter
    def folder_name(self, folder_name):
        """
        Sets the folder_name of this ExistingSource.

        :param folder_name: The folder_name of this ExistingSource.
        :type: str
        """

        self._folder_name = folder_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ExistingSource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
