# coding: utf-8

"""
    Wealthport API

    Wealthport provides a simple, lightweight and open Web API based on the Open API 2.0 standard (<a href=\"https://www.openapis.org\" target=\"_blank\">https://www.openapis.org</a>). Our APIs offer a variety of operations related to managing Sources, Folders, Orders and Recipes. There are operations to submit and track Jobs, upload and download data files and many more.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ExistingFolder(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'created': 'datetime',
        'creator': 'str',
        'bytes': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'created': 'created',
        'creator': 'creator',
        'bytes': 'bytes'
    }

    def __init__(self, id=None, name=None, created=None, creator=None, bytes=None):
        """
        ExistingFolder - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._created = None
        self._creator = None
        self._bytes = None

        self.id = id
        self.name = name
        self.created = created
        self.creator = creator
        self.bytes = bytes

    @property
    def id(self):
        """
        Gets the id of this ExistingFolder.
        Unique ID of the folder

        :return: The id of this ExistingFolder.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ExistingFolder.
        Unique ID of the folder

        :param id: The id of this ExistingFolder.
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")
        if id is not None and len(id) > 36:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `36`")
        if id is not None and len(id) < 36:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `36`")

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this ExistingFolder.
        Name of the folder

        :return: The name of this ExistingFolder.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ExistingFolder.
        Name of the folder

        :param name: The name of this ExistingFolder.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name

    @property
    def created(self):
        """
        Gets the created of this ExistingFolder.
        ISO 8601 Date when he folder has been created

        :return: The created of this ExistingFolder.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this ExistingFolder.
        ISO 8601 Date when he folder has been created

        :param created: The created of this ExistingFolder.
        :type: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")

        self._created = created

    @property
    def creator(self):
        """
        Gets the creator of this ExistingFolder.
        User ID of the user who created the folder

        :return: The creator of this ExistingFolder.
        :rtype: str
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """
        Sets the creator of this ExistingFolder.
        User ID of the user who created the folder

        :param creator: The creator of this ExistingFolder.
        :type: str
        """
        if creator is None:
            raise ValueError("Invalid value for `creator`, must not be `None`")
        if creator is not None and len(creator) > 36:
            raise ValueError("Invalid value for `creator`, length must be less than or equal to `36`")
        if creator is not None and len(creator) < 36:
            raise ValueError("Invalid value for `creator`, length must be greater than or equal to `36`")

        self._creator = creator

    @property
    def bytes(self):
        """
        Gets the bytes of this ExistingFolder.
        Size of the folder (in bytes)

        :return: The bytes of this ExistingFolder.
        :rtype: int
        """
        return self._bytes

    @bytes.setter
    def bytes(self, bytes):
        """
        Sets the bytes of this ExistingFolder.
        Size of the folder (in bytes)

        :param bytes: The bytes of this ExistingFolder.
        :type: int
        """
        if bytes is None:
            raise ValueError("Invalid value for `bytes`, must not be `None`")
        if bytes is not None and bytes < -1:
            raise ValueError("Invalid value for `bytes`, must be a value greater than or equal to `-1`")

        self._bytes = bytes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ExistingFolder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
